server {
  listen 80;
  server_name _;
  proxy_set_header Host $http_host;
  proxy_set_header X-Forwarded-Host $http_host;
  proxy_set_header X-Forwarded-Proto $scheme;
  location = / { return 302 /performanceV2/; }
  location /performanceV2/ { proxy_pass http://frontend; }
  location /api/performance/ { proxy_pass http://api:8080/api/; }
  location /api/ { proxy_pass http://core:8080/api/; }
  location /performance-api/api/v1/auth/ { proxy_pass http://core:8080/api/v1/auth/; }
  location /performance-api/api/v2/auth/ { proxy_pass http://core:8080/api/v2/auth/; }
  location /performance-api/api/performance/ { proxy_pass http://api:8080/api/; }
  location /performance-api/ { proxy_pass http://api:8080/; }
  location /core/ { proxy_pass http://core:8080/; }
  location /sso { proxy_pass http://sso:3000; }
}
